Repository CrashpointF13/CrashpointF13, pull requests merged in 2020-06, with the labels that each got.

#64 Reduced Armor Slowdown/Increase all around
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
Labels: Testmerged

#65 Primitive Farming Implements - Wooden Rakes, Wood Buckets + Crafting DM restructure.
  code/modules/crafting/recipes.dm
  code/modules/hydroponics/hydroitemdefines.dm
  code/modules/reagents/reagent_containers/glass.dm
  icons/mob/head.dmi
  icons/mob/inhands/equipment/custodial_lefthand.dmi
  icons/mob/inhands/equipment/custodial_righthand.dmi
  icons/mob/inhands/equipment/hydroponics_lefthand.dmi
  icons/mob/inhands/equipment/hydroponics_righthand.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/janitor.dmi
Labels: Awaiting Merge, Testmerged

#69 Changes Ghouls from Bullet Sponges back to How They Used To Be
  code/modules/mob/living/simple_animal/hostile/ghoul.dm
Labels: Awaiting Merge, Balance/Rebalance

#70 throwing spears buff
  code/game/objects/items/weaponry.dm
Labels: Awaiting Merge, Balance/Rebalance

#71 Stuff
  code/game/objects/effects/portals.dm
  code/game/objects/items/crayons.dm
  code/game/objects/structures/crates_lockers/crates/wooden.dm
  code/modules/hydroponics/grown/banana.dm
  code/modules/vending/liberation_toy.dm
  code/modules/vending/toys.dm
  strings/traumas.json
Labels: Awaiting Merge

#74 libritor nerf
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
Labels: Awaiting Merge, Testmerged

#76 Adminwho
  code/modules/client/verbs/who.dm
Labels: Awaiting Merge

#81 Abandon Wasteland
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/vote.dm
Labels: Config Update

#83 Medical crafting rework.
  code/modules/crafting/recipes.dm
Labels: Balance/Rebalance

#86 Reverting Molotovs
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
Labels: Balance/Rebalance

#97 Transfer Tweak
  code/controllers/subsystem/vote.dm
Labels: Awaiting Merge, Bugfix

#95 Removes a stupid DR thing.
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/fallout/obj/items.dm
  icons/fallout/objects/items.dmi
Labels: Awaiting Merge

#94 Ammo Crafting Fixes and Tweaks
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Pahrump/Pahrump.dmm
  code/modules/crafting/recipes.dm
Labels: Balance/Rebalance, Testmerged

#103 Removes H&K CAWS and City-Killer Shotgun from crafting
  code/modules/crafting/recipes.dm
Labels: Awaiting Merge

#115 Fixes the train on Pahrump.
  _maps/map_files/Pahrump/Pahrump.dmm
Labels: Map Change

#121 fixes some areas in sunnydale (but works)
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Awaiting Merge, Map Change

#122 Small Armor Tweaks and Fixes
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
Labels: Awaiting Merge, Balance/Rebalance

#112 [READY] Adds back enclave powerarmor to the T5 armor pool also removes ring.
  code/game/objects/effects/spawners/f13lootdrop.dm
Labels: Awaiting Merge

#118 NCR Base & Misc Changes Redux
  _maps/map_files/Pahrump/Pahrump.dmm
Labels: Map Change

#128 Some loot spawn tweaks and big radscorp cave.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Pahrump/Dungeons.dmm
  _maps/map_files/Pahrump/Pahrump.dmm
Labels: Map Change

#129 Tesla powerarmor is now medium armor.
  code/modules/clothing/suits/armor.dm
Labels: Balance/Rebalance

#85 Tweaks Turbo and Adds Antivenom
  code/modules/crafting/recipes.dm
  code/modules/fallout/obj/food_and_drinks/food.dm
  code/modules/mob/living/simple_animal/hostile/wasteanimals.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/reagent_containers/bottle.dm
  icons/obj/chemical.dmi
  icons/obj/food/food.dmi
Labels: Balance/Rebalance, Testmerged

#84 guns/laser/ht helmet fixes
  code/game/objects/items/shields.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/launchers.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets/lmg.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  code/modules/projectiles/projectile/bullets/revolver.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  code/modules/projectiles/projectile/bullets/smg.dm
  code/modules/projectiles/projectile/bullets/sniper.dm
  code/modules/projectiles/projectile/reusable/_reusable.dm
Labels: Balance/Rebalance, Testmerged
